### ISSUE TITLE
Add as a new maintainer

### ISSUE THREAD

**Issue by millimelon** [TheEvergreenStateCollege/lower-division-cs#11]
I would appreciate being added as a maintainer for our collective class coding assignments.

**Comment by learner-long-life** [comment]
go go maintainers 

<img width="1068" alt="image" src="https://github.com/TheEvergreenStateCollege/lower-division-cs/assets/148553/0ee52e41-2800-4061-8e20-4b3d4e92dbd1">

Classmates that are already maintainers can click "Settings", "Collaborators and teams", "Add people" and type in your username @2001ladybug   and click "Add" with "maintainer" permissions. @Andersen-Ader @rreeman @Studbug please let us know here when you do by posting a comment here, and @2001ladybug   can accept the invite.

@2001ladybug  when you yourself are maintainer, you're invited to check open issues like this when you can and help add other classmates who request it.

**Comment by rreeman** [comment]
Sent you an invite. Welcome
