### ISSUE TITLE
Add as new maintainer 

### ISSUE THREAD

**Issue by RyleeC99** [TheEvergreenStateCollege/lower-division-cs#5]
please add me, thank you :)

**Comment by learner-long-life** [comment]
go go maintainers @Andersen-Ader @rreeman @Studbug 

<img width="1068" alt="image" src="https://github.com/TheEvergreenStateCollege/lower-division-cs/assets/148553/0ee52e41-2800-4061-8e20-4b3d4e92dbd1">

Classmates that are already maintainers can click "Settings", "Collaborators and teams", "Add people" and type in your username @RyleeC99  and click "Add" with "maintainer" permissions. Please let us know here when you do, and Rylee can accept the invite.

**Comment by rreeman** [comment]
Hi @learner-long-life . I don't have those options available on my Settings page. 
<img width="777" alt="Screenshot (9782)" src="https://github.com/TheEvergreenStateCollege/lower-division-cs/assets/24871347/4dd7761f-29e1-48f3-8109-d99635413dfc">

**Comment by learner-long-life** [comment]
my bad @rreeman try again, and add new classmates as *admin*s not *maintainer*s.
Admins have permission to add new collaborators, and all classmates should have that. Thanks.

**Comment by rreeman** [comment]
invited, welcome
