### ISSUE TITLE
Add as new maintainer

### ISSUE THREAD

**Issue by wooJake** [TheEvergreenStateCollege/lower-division-cs#6]
Please add me to the lower division cs as a maintainer, thank you.

**Comment by learner-long-life** [comment]
go go maintainers @Andersen-Ader @rreeman @Studbug 

<img width="1068" alt="image" src="https://github.com/TheEvergreenStateCollege/lower-division-cs/assets/148553/0ee52e41-2800-4061-8e20-4b3d4e92dbd1">

Classmates that are already maintainers can click "Settings", "Collaborators and teams", "Add people" and type in your username @RyleeC99  and click "Add" with "maintainer" permissions. Please let us know here when you do, and @wooJake  can accept the invite.

@wooJake after you are a maintainer, you are invited to check open issues when you can and add future classmates who request it.

**Comment by rreeman** [comment]
Sent you an invite. Welcome
