### ISSUE TITLE
Add as new maintainer

### ISSUE THREAD

**Issue by AllieUDUC** [TheEvergreenStateCollege/lower-division-cs#7]
Please add me as a maintainer as per the Monorepo and Gitpod assignment.

**Comment by learner-long-life** [comment]
go go maintainers @Andersen-Ader @rreeman @Studbug 

<img width="1068" alt="image" src="https://github.com/TheEvergreenStateCollege/lower-division-cs/assets/148553/0ee52e41-2800-4061-8e20-4b3d4e92dbd1">

Classmates that are already maintainers can click "Settings", "Collaborators and teams", "Add people" and type in your username @RyleeC99  and click "Add" with "maintainer" permissions. Please let us know here when you do, and Rylee can accept the invite.

**Comment by rreeman** [comment]
Sent you an invite. Welcome

**Comment by RyleeC99** [comment]
Thank you, I have accepted the invite

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
