### ISSUE TITLE
Add new maintainer

### ISSUE THREAD

**Issue by Danifey** [TheEvergreenStateCollege/lower-division-cs#8]
i would like to be added as a new maintainer. Dani (they/them) CSF-2

**Comment by learner-long-life** [comment]
go go maintainers @Andersen-Ader @rreeman @Studbug 

<img width="1068" alt="image" src="https://github.com/TheEvergreenStateCollege/lower-division-cs/assets/148553/0ee52e41-2800-4061-8e20-4b3d4e92dbd1">

Classmates that are already maintainers can click "Settings", "Collaborators and teams", "Add people" and type in your username @Danifey  and click "Add" with "maintainer" permissions. Please let us know here when you do, and @Danifey  can accept the invite and close this issue.

**Comment by rreeman** [comment]
Sent you an invite. Welcome
