### ISSUE TITLE
Add as new maintainer

### ISSUE THREAD

**Issue by coopercode123** [TheEvergreenStateCollege/lower-division-cs#9]
I would like to be added as a maintainer (Cooper Benzing CSF spring 2024)

**Comment by learner-long-life** [comment]
added, welcome

**Comment by learner-long-life** [comment]
You can close this issue after you accept your invite (check your email, or watch your GitHub inbox for a blue dot notification)

<img width="1068" alt="image" src="https://github.com/TheEvergreenStateCollege/lower-division-cs/assets/148553/0ee52e41-2800-4061-8e20-4b3d4e92dbd1">

Classmates that are already maintainers can click "Settings", "Collaborators and teams", "Add people" and type in your username @RyleeC99  and click "Add" with "maintainer" permissions.

After you are a maintainer, you are welcome to check open issues when you can and add future classmates who request it.
